Repository ManageIQ/manageiq-release, pull requests merged in 2020-08, with the labels that each got.

#142 Add release task to manageiq-rpm_build
  config/repos.yml
Labels: enhancement

#144 Add IBM Cloud Provider
  config/labels.yml
  config/repos.yml
Labels: enhancement

#145 Revamp new repo scripts to focus on new plugin repos
  bin/new_js_repo.rb
  bin/new_plugin_repo.rb
  bin/new_ruby_repo.rb
  bin/update_labels.rb
  lib/manageiq/release/code_climate.rb
  lib/manageiq/release/travis.rb
  lib/manageiq/release/update_labels.rb
  scripts/pull_request_blaster_outer/new_js_repo.rb
  scripts/pull_request_blaster_outer/new_plugin_repo.rb
  scripts/pull_request_blaster_outer/new_ruby_repo.rb
Labels: cleanup, refactoring

#146 Refactor Dir.chdir into repo.chdir
  bin/destroy_branch.rb
  bin/fetch_repos.rb
  bin/release_microservice.rb
  bin/update_sources_for_new_branch.rb
  lib/manageiq/release/pull_request_blaster_outer.rb
  lib/manageiq/release/release_branch.rb
  lib/manageiq/release/repo.rb
Labels: refactoring

#147 NSX-T Provider to be introduced in Kasparov
  config/labels.yml
Labels: developer

#148 Standardize on repo_set terminology
  bin/destroy_branch.rb
  bin/destroy_tag.rb
  bin/fetch_repos.rb
  bin/list_backport_pr.rb
  bin/new_plugin_repo.rb
  bin/pull_request_blaster_outer.rb
  bin/release_branch.rb
  bin/release_microservice.rb
  bin/release_milestone.rb
  bin/release_tag.rb
  bin/rename_labels.rb
  bin/show_commit_history.rb
  bin/show_repo_set.rb
  bin/show_tag.rb
  bin/show_travis_status.rb
  bin/update_branch_protection.rb
  bin/update_labels.rb
  bin/update_repo_settings.rb
  bin/update_sources_for_new_branch.rb
  lib/manageiq/release.rb
  lib/manageiq/release/destroy_tag.rb
  lib/manageiq/release/release_branch.rb
  lib/manageiq/release/repo_set.rb
Labels: refactoring

#149 Simplify CLI to class interface by ignoring extra keywords
  bin/destroy_tag.rb
  bin/new_plugin_repo.rb
  bin/pull_request_blaster_outer.rb
  bin/release_branch.rb
  bin/release_milestone.rb
  bin/release_tag.rb
  bin/rename_labels.rb
  bin/update_branch_protection.rb
  bin/update_labels.rb
  bin/update_repo_settings.rb
  lib/manageiq/release/code_climate.rb
  lib/manageiq/release/destroy_tag.rb
  lib/manageiq/release/hakiri.rb
  lib/manageiq/release/license.rb
  lib/manageiq/release/pull_request_blaster_outer.rb
  lib/manageiq/release/readme_badges.rb
  lib/manageiq/release/release_branch.rb
  lib/manageiq/release/release_milestone.rb
  lib/manageiq/release/release_tag.rb
  lib/manageiq/release/rename_labels.rb
  lib/manageiq/release/travis.rb
  lib/manageiq/release/update_branch_protection.rb
  lib/manageiq/release/update_labels.rb
  lib/manageiq/release/update_repo_settings.rb
Labels: cleanup

#153 More changes for converting branch to repo_set
  lib/manageiq/release/repo_set.rb
Labels: cleanup

#152 Allow mirror on repos that don't start with manageiq-
  .gitignore
  config/settings.yml
  config/settings/test.yml
  lib/manageiq/release/git_mirror.rb
Labels: enhancement
