Repository ManageIQ/manageiq-release, pull requests merged in 2021-03, with the labels that each got.

#191 Add Oracle Cloud provider
  config/labels.yml
  config/repos.sets.yml
  config/repos.yml
  config/settings.yml
Labels: enhancement

#192 Add destroy_remote script
  bin/destroy_remote.rb
Labels: enhancement

#193 Add backport_prs script
  bin/backport_prs.rb
  bin/show_backport_prs.rb
  lib/manageiq/release.rb
  lib/manageiq/release/backport_prs.rb
  lib/manageiq/release/git_mirror.rb
  lib/manageiq/release/string_formatting.rb
Labels: enhancement

#194 Prevent backports when conflicts label still exists
  bin/backport_prs.rb
  lib/manageiq/release/backport_prs.rb
Labels: enhancement

#195 Put back accidental removal of Settings require
  lib/manageiq/release/git_mirror.rb
Labels: bug

#196 Merge show_backport_prs into backport_prs as a CLI option
  bin/backport_prs.rb
  bin/show_backport_prs.rb
  lib/manageiq/release/backport_prs.rb
Labels: refactoring

#197 Use standard :strings type for labels list
  bin/backport_prs.rb
Labels: enhancement

#198 Rename semver labels
  config/labels.yml
Labels: enhancement

#199 Do not remove the yes label when finding a conflict
  lib/manageiq/release/backport_prs.rb
Labels: bug

#200 Drop labels from gaprindashvili or prior
  config/labels.yml
Labels: technical debt
