Repository ManageIQ/manageiq-release, pull requests merged in 2021-02, with the labels that each got.

#182 Add wim_parser repo
  config/repos.other.yml
  scripts/pull_request_blaster_outer/new_plugin_repo.rb
Labels: enhancement

#183 Allow for other GitHub endpoints, such as GitHub Enterprise
  lib/manageiq/release.rb
Labels: enhancement

#185 Add tshirt sizing labels to all repos
  config/labels.yml
Labels: enhancement

#184 Consistent options grammar
  lib/manageiq/release.rb
Labels: cleanup

#186 Add VERSIONS.md file
  VERSIONS.md
Labels: documentation, enhancement

#187 Updates for lasker branch
  config/labels.yml
  config/repos.yml
Labels: enhancement

#189 Add tool to create a rubygems stub for new git-based repos
  bin/new_plugin_repo.rb
  bin/new_rubygems_stub.rb
  lib/manageiq/release.rb
  lib/manageiq/release/rubygems_stub.rb
Labels: enhancement

#190 Add workaround for labels with '?'
  lib/manageiq/release/update_labels.rb
Labels: bug
