Repository ManageIQ/manageiq-release, pull requests merged in 2022-09, with the labels that each got.

#263 Use explicit keyword arguments where they're expected
  bin/pull_request_blaster_outer.rb
Labels: ruby3

#264 Script updating rubygems.manageiq.org/index.html
  bin/miq_gem_push.rb
Labels: enhancement

#265 Fix index.html not working
  bin/miq_gem_push.rb
Labels: bug
